### ISSUE TITLE
Run from the url

### ISSUE THREAD

**Issue by getsetbro** [jonathantneal/closest-color#1]
An idea is to make it linkable like: http://jonathantneal.github.io/closest-color/00aced

**Comment by jonathantneal** [comment]
As far as I know, GitHub pages do not allow for wildcard redirections, so the URL would need to be slightly less beautiful, probably through a hash like `https://jonathantneal.github.io/closest-color/#00aced`.

**Comment by jonathantneal** [comment]
Added as of https://github.com/jonathantneal/closest-color/commit/5c16fd86c75920b3d09db12fbfe0a605ad145355

Example: https://jonathantneal.github.io/closest-color/#f03e25

**Comment by getsetbro** [comment]
love it love it love it
