### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by joaocunha** [jonathantneal/closest-color#2]
Any plans on publishing it to npm?

**Comment by jonathantneal** [comment]
Sure. I was also thinking of separating the colors into their own repo. What advantages would there be to having this portion on npm?

**Comment by joaocunha** [comment]
I think it's useful to have the colors themselves in a separate repo, and work towards better standardizing them across the community.

Other than that, exposing the functionality of the lib as an API would be the initial step towards #3.

```
$ closestcolor '#ff8c01'
{
  name: 'Dark Orange',
  hex: '#ff8c01'
}
```

Options could define the return format (RGB/Hex), name-only, color code-only, etc.

**Comment by jonathantneal** [comment]
Ah yes, from the CLI. Very useful. Let me look into that.

**Comment by jonathantneal** [comment]
Okay, this is in with https://github.com/jonathantneal/closest-color/commit/f344db64a9b98917080bbf61b7f60871392c23b3

**Comment by joaocunha** [comment]
:100: :exclamation:
